server:
  port: 8080

spring:
  application:
    name: api-gateway`
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://USERSERVICE
              predicates:
                - Path=/user/**
              filters:
                - RewritePath=/user/(?<segment>.*), /${segment}
                - CircuitBreaker=UserServiceCircuitBreaker


            - id: product-service
              uri: lb://PRODUCTSERVICE
              predicates:
                - Path=/products/**
              filters:
                - RewritePath=/products/(?<segment>.*), /${segment}

            - id: inventory-service
              uri: lb://INVENTORYSERVICE
              predicates:
                - Path=/inventory/**
              filters:
                - RewritePath=/inventory/(?<segment>.*), /${segment}

            - id: order-service
              uri: lb://ORDERSERVICE
              predicates:
                - Path=/order/**
              filters:
                - RewritePath=/order/(?<segment>.*), /${segment}

            - id: payment-service
              uri: lb://PAYMENTSERVICE
              predicates:
                - Path=/payment/**
              filters:
                - RewritePath=/payment/(?<segment>.*), /${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

resilience4j:
    circuitbreaker:
      instances:
        UserServiceCircuitBreaker:
          failure-rate-threshold: 50
          minimum-number-of-calls: 5
          sliding-window-size: 10
          wait-duration-in-open-state: 10s
          permitted-number-of-calls-in-half-open-state: 2


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
   name: ${spring.application.name}
   description: ApiGateway Microservice
   version: 1.0.0



